### ISSUE TITLE
AccountOverview Alerts & Navigation Items

### ISSUE THREAD

**Issue by pauljohanneskraft** [StanfordSpezi/SpeziAccount#77] opened 2024-10-28 18:10 UTC
### Description

When the user is on the AccountOverview screen (i.e. the one when one is already logged in and wants to see all the details of the user), some of the features are not working as expected. This includes that navigation items disappear and the logout alert is not shown.

### Reproduction

Have an AccountOverview screen (possibly with lots of AccountKey-UI being shown) and then scroll down and/or try to log out or delete account.

### Expected behavior

The navigation Items stay visible and the logout/delete alert is shown.

### Additional context

[Video Recording](https://github.com/user-attachments/assets/9d9cd4b8-a51e-4e25-abb1-c482eacaa645)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by Supereg** [comment] 2024-10-28 19:55
Oh, great catch there 🚀 

 The issue is, that we currently add all modifiers to the account header which is not visible anymore once you scroll down. See here: https://github.com/StanfordSpezi/SpeziAccount/blob/7ef29a7743c01a083ba69e93479e82d3be199ac0/Sources/SpeziAccount/Views/AccountOverview/AccountOverviewSections.swift#L67-L167

The original implementation did that as we experienced huge issues with the way the `editMode` environment variable and the `EditButton` view is implemented. See our code comment here:
https://github.com/StanfordSpezi/SpeziAccount/blob/7ef29a7743c01a083ba69e93479e82d3be199ac0/Sources/SpeziAccount/AccountOverview.swift#L92-L93

We would need to move all these modifiers out to the `AccountOverview` view and attach it to the List view. We would need to check if we still experience the same issues with EditMode and the EditButton placement.

I can tackle this issue in my currently open PR https://github.com/StanfordSpezi/SpeziAccount/pull/76 and get this merged in the final 2.0 release.

**Comment by pauljohanneskraft** [comment] 2024-10-28 21:13
Thank you very much @Supereg ! Sounds great, let me know if I can provide any help 😊

**Comment by PSchmiedmayer** [comment] 2024-10-29 01:59
Amazing; thank you @Supereg!

**Closed** 2024-10-31 11:46 UTC
Labels: bug
